### PR TITLE
caBundle file path

### PR DESCRIPTION
**Pull request by inri13666**
this PR allows customize caBundle file path or negotiate from PHP settings if presented

### CODE REVIEW

**Comment by rolftimmermans** [comment]
Thanks for your contribution! May I ask what the motivation is for this request? The CA bundle included in the client library so that no one has to configure their root certificates. I would like to understand why you have the need to provide a different set of roots?

**Comment by inri13666** [comment]
The reasons are simple:
1. at the current moment, your library cannot be wrapped as PHAR archive (https://github.com/inri13666/phar-TinyPNG) because you use a hardcoded path to "caBundle file"
2. if PHP setting "curl.cainfo" is configured, then I assume this certificate should be used because it can be custom.

**Comment by rolftimmermans** [comment]
If the CA bundle were included in the PHAR archive, wouldn't it be possible to read it similar to how it's being read right now? What are the specific issues you are running into?

**Comment by inri13666** [comment]
If it inside "PHAR" archive then it can't be accessed by cURL library, but PHP can handle it

**Comment by peter279k** [comment]
Actually, the `cabundle` path should not be set. In general, the `cabundle` file path will be correct to be set in Operating system. Such as Ubuntu.
This work should be done by developers, and the PHP package should not do this.

**Comment by inri13666** [comment]
@peter279k look at this code https://github.com/tinify/tinify-php/blob/master/lib/Tinify/Client.php#L19
The `cabundle` path is hardcoded, the goal for this pull request to give developers ability to set custom path.
In case 'pharized' library, as you know, the cURL library unable to access this file, because first of all it's hardcoded and secondary it's inside the archive.

**Comment by inri13666** [comment]
absolutely agree, that library should support a non-hardcoded way for configuring CA bundle.
For my "phar" version, I have solved it, and share the solution here, to allow other developers to manually configure the path to CA Bundle

**Pull request closed without merging**
